apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
        version: beta-{{gitops.version}}
        deploy: {{gitops.deploy}}
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always

          args: 
          - --sleep
          - "1000"
          - --run-loop
          - --server
          - http://ngsa-memory:8080
          - --files
          - benchmark.json
          - --prometheus
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-np
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}

spec:
  type: NodePort
  selector:
    app: {{gitops.name}}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
